from core import *

# Generated by build.py\n#

# all

# elements


# Predefined elements
# noinspection DuplicatedCode
class ANCHOR(Element):
    def __init__(self, *children, **attributes):
        super().__init__(*children, **attributes)
        self._tag = "a"


# noinspection DuplicatedCode
class DOCTYPE:
    def __init__(self, document_type: str = "html"):
        """Returns a DOCTYPE element. Currently, only supports html."""
        self.document_type = document_type

    def __str__(self):
        return f"<!DOCTYPE {self.document_type}>"


# noinspection DuplicatedCode
class COMMENT:
    """Returns an html comment."""

    def __init__(self, text: str):
        self.text = text

    def __str__(self):
        return f"<!-- {self.text} -->"


# noinspection DuplicatedCode
class TEXTAREA(Element):
    """Returns a textarea element. It uses the same attributes as a <input type="textarea">"""

    def __str__(self):
        properties = self._attributes
        content = properties["_value"] if "_value" in properties.keys() else ""
        if "_value" in self._attributes.keys():
            del self._attributes["_value"]
        return f"<textarea{core.mk_props(self._attributes)}>{content}</textarea>"

